# 1. Create a PyTorch tensor of shape (4, 5, 6) and print its shape.


In [2]:
import torch 

x = torch.randn(4, 5, 6)
print(x.shape)

torch.Size([4, 5, 6])


In [3]:
x

tensor([[[ 0.5424, -0.2931, -0.8021,  0.5595, -1.1227,  0.0396],
         [-0.9587, -1.5957, -0.6255,  1.4483,  0.5464,  0.4696],
         [-0.2321,  0.7796, -0.7689, -1.1717,  1.0971, -0.5971],
         [-0.5979, -0.0941, -1.0825, -1.2903, -0.9445, -1.4213],
         [-0.4206,  0.6984,  0.6119,  0.2494, -0.5277,  0.5165]],

        [[ 0.6071, -0.8841,  0.3592, -0.6317,  0.3466,  0.3778],
         [ 0.3620, -0.9219,  0.5255,  0.2668,  0.1373,  0.0113],
         [-0.0655, -0.2892,  0.1604,  1.2970,  0.1647, -0.3927],
         [-0.2085,  0.4432,  0.4142,  0.1113,  0.3335, -0.6126],
         [-0.3825,  0.2960, -0.7009,  0.3475, -0.3747,  0.8803]],

        [[-1.0224, -0.1385, -3.3821, -0.4973,  2.1513,  0.8874],
         [-1.0507, -0.0216, -0.1224,  1.0162,  1.0195, -0.0670],
         [-1.0843, -0.7465, -0.4270, -0.0827, -2.0698, -0.1592],
         [-1.1024,  0.8638,  1.7990, -0.7687, -0.7379,  0.0252],
         [-1.0005, -0.3499,  0.0342, -0.3889,  0.6558, -0.0660]],

        [[-0.3118, 

In [5]:
torch.rand(torch.Size([2, 3]))

tensor([[0.8700, 0.2121, 0.0152],
        [0.9494, 0.7914, 0.4058]])

# 2. Convert a (6, 6) tensor into a 1D tensor and print its new shape.

In [8]:
x = torch.rand(6,6)
x

tensor([[0.2968, 0.2823, 0.0382, 0.8574, 0.8279, 0.6397],
        [0.5217, 0.6609, 0.5673, 0.0543, 0.6257, 0.0629],
        [0.8049, 0.9633, 0.4230, 0.4368, 0.4029, 0.1160],
        [0.7128, 0.9143, 0.3205, 0.9649, 0.8933, 0.1573],
        [0.1593, 0.2516, 0.8897, 0.5905, 0.8879, 0.8081],
        [0.8628, 0.9912, 0.5598, 0.2070, 0.4357, 0.2252]])

In [10]:
x.flatten().shape

torch.Size([36])

# 3. Given a tensor A of shape (10,), use .unsqueeze() to make it:
A 2D tensor with shape (1, 10)
A 2D tensor with shape (10, 1)

In [11]:
a = torch.arange(10)
a.shape

torch.Size([10])

In [12]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a.unsqueeze(0).shape, a.unsqueeze(1).shape , a.unsqueeze(-1).shape

(torch.Size([1, 10]), torch.Size([10, 1]), torch.Size([10, 1]))

#  4. Given a tensor of shape (1, 3, 1, 5), remove all dimensions of size 1 using .squeeze()

In [16]:
# Given a tensor of shape (1, 3, 1, 5)

x = torch.rand(1, 3, 1, 5)

x.squeeze(dim=0).squeeze(dim=1).shape 

torch.Size([3, 5])

In [17]:
# Given a tensor of shape (1, 3, 1, 5), remove all dimensions of size 1 using .squeeze().

x = torch.rand(1, 3, 1, 5)
x.squeeze().shape

torch.Size([3, 5])

# 5. Swap the last two dimensions of a tensor with shape (3, 4, 5)

In [18]:
x = torch.rand(3,4,5)

x.permute(0,2,1).shape

torch.Size([3, 5, 4])

# 6. Transpose a tensor of shape (5, 3) into (3, 5).

In [19]:
x = torch.rand(5,3)

x.t().shape

torch.Size([3, 5])

# 7. Create a batch of 8 images, where each image has 3 color channels and a height & width of (32, 32). What will be the shape?

In [20]:
height = 32
width = 32
channels = 3
batch_size = 8

x = torch.rand(batch_size, channels, height, width)

x.shape

torch.Size([8, 3, 32, 32])

# 8. Reshape a tensor of shape (4, 5, 6) into shape (20, 6).

In [21]:
x = torch.randn(4, 5, 6)

x.view(-1, 6).shape

torch.Size([20, 6])

In [22]:
# now using reshape
x = torch.randn(4, 5, 6)
x.reshape(20, 6).shape

torch.Size([20, 6])

# 9. Concatenate two tensors of shape (3, 4) along:
The first dimension
The second dimension

In [24]:
x1 = torch.rand(3, 4)
x2 = torch.rand(3, 4)

x1 , x2

(tensor([[0.1792, 0.1917, 0.9878, 0.8619],
         [0.8051, 0.9617, 0.1398, 0.2457],
         [0.2861, 0.3415, 0.8836, 0.3609]]),
 tensor([[0.2154, 0.7540, 0.5638, 0.3283],
         [0.2195, 0.7004, 0.9558, 0.7102],
         [0.6117, 0.4243, 0.2084, 0.2956]]))

In [26]:
torch.cat((x1, x2), dim=0)

tensor([[0.1792, 0.1917, 0.9878, 0.8619],
        [0.8051, 0.9617, 0.1398, 0.2457],
        [0.2861, 0.3415, 0.8836, 0.3609],
        [0.2154, 0.7540, 0.5638, 0.3283],
        [0.2195, 0.7004, 0.9558, 0.7102],
        [0.6117, 0.4243, 0.2084, 0.2956]])

In [27]:
torch.cat((x1, x2), dim=1)

tensor([[0.1792, 0.1917, 0.9878, 0.8619, 0.2154, 0.7540, 0.5638, 0.3283],
        [0.8051, 0.9617, 0.1398, 0.2457, 0.2195, 0.7004, 0.9558, 0.7102],
        [0.2861, 0.3415, 0.8836, 0.3609, 0.6117, 0.4243, 0.2084, 0.2956]])

# 10. Stack two tensors of shape (2, 3) along a new dimension. What will be the shape?

In [32]:
x1 = torch.rand(2,3)
x2 = torch.rand(2,3)
x1, x2

(tensor([[0.2621, 0.8349, 0.3254],
         [0.0773, 0.3703, 0.2239]]),
 tensor([[0.9935, 0.3075, 0.2297],
         [0.8294, 0.6323, 0.5691]]))

In [ ]:
torch.stack((x1, x2), dim=0)

tensor([[[0.2621, 0.8349, 0.3254],
         [0.0773, 0.3703, 0.2239]],

        [[0.9935, 0.3075, 0.2297],
         [0.8294, 0.6323, 0.5691]]])

In [34]:
torch.stack((x1, x2), dim=0).shape

torch.Size([2, 2, 3])

# 11. Expand a tensor of shape (4, 1) into (4, 10) without copying memory.

In [36]:
x = torch.rand(4,1)

x

tensor([[0.4241],
        [0.8177],
        [0.8600],
        [0.6294]])

In [39]:
x.expand(4, 10)

tensor([[0.4241, 0.4241, 0.4241, 0.4241, 0.4241, 0.4241, 0.4241, 0.4241, 0.4241,
         0.4241],
        [0.8177, 0.8177, 0.8177, 0.8177, 0.8177, 0.8177, 0.8177, 0.8177, 0.8177,
         0.8177],
        [0.8600, 0.8600, 0.8600, 0.8600, 0.8600, 0.8600, 0.8600, 0.8600, 0.8600,
         0.8600],
        [0.6294, 0.6294, 0.6294, 0.6294, 0.6294, 0.6294, 0.6294, 0.6294, 0.6294,
         0.6294]])

# 12. Given A of shape (4, 5, 6), reshape it into (4, 30), then reshape it back to (4, 5, 6)

In [41]:
x = torch.rand(4, 5, 6)

x.view(4, -1).shape

torch.Size([4, 30])

In [42]:
x.view(4, -1).view(4, 5, 6).shape

torch.Size([4, 5, 6])

In [43]:
x == x.view(4, -1).view(4, 5, 6)

tensor([[[True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True]],

        [[True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True]],

        [[True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True]],

        [[True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True]]])

# 13. Given two tensors:
A of shape (3, 1, 4)
B of shape (1, 2, 4)
What will be their broadcasted shape when added together?

In [48]:
torch.manual_seed(42)

a = torch.rand(3,1,4)
b = torch.rand(1,2,4)

a , b

(tensor([[[0.8823, 0.9150, 0.3829, 0.9593]],
 
         [[0.3904, 0.6009, 0.2566, 0.7936]],
 
         [[0.9408, 0.1332, 0.9346, 0.5936]]]),
 tensor([[[0.8694, 0.5677, 0.7411, 0.4294],
          [0.8854, 0.5739, 0.2666, 0.6274]]]))

In [50]:
(a + b).shape

torch.Size([3, 2, 4])

In [51]:
a + b

tensor([[[1.7517, 1.4827, 1.1240, 1.3887],
         [1.7677, 1.4889, 0.6494, 1.5868]],

        [[1.2599, 1.1686, 0.9977, 1.2230],
         [1.2759, 1.1748, 0.5232, 1.4211]],

        [[1.8102, 0.7009, 1.6757, 1.0230],
         [1.8262, 0.7071, 1.2012, 1.2210]]])

In [54]:
0.9150 + 0.5677

1.4827

In [55]:
0.9150 + 0.5739

1.4889000000000001

In [56]:
a = torch.arange(12).reshape(3,1,4)
a

tensor([[[ 0,  1,  2,  3]],

        [[ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11]]])

In [60]:
b = torch.arange(8).reshape(1,2,4)
b

tensor([[[0, 1, 2, 3],
         [4, 5, 6, 7]]])

In [61]:
a + b

tensor([[[ 0,  2,  4,  6],
         [ 4,  6,  8, 10]],

        [[ 4,  6,  8, 10],
         [ 8, 10, 12, 14]],

        [[ 8, 10, 12, 14],
         [12, 14, 16, 18]]])

In [62]:
a = torch.arange(12).view(3,1,4)
b = torch.arange(8).view(1,2,4)

a + b

tensor([[[ 0,  2,  4,  6],
         [ 4,  6,  8, 10]],

        [[ 4,  6,  8, 10],
         [ 8, 10, 12, 14]],

        [[ 8, 10, 12, 14],
         [12, 14, 16, 18]]])

# 14. Perform element-wise addition on tensors of shape (2, 1, 5) and (1, 3, 5). What will be the resulting shape?

In [63]:
a = torch.arange(10).reshape(2,1,5)
b = torch.arange(15).reshape(1,3,5)

a, b

(tensor([[[0, 1, 2, 3, 4]],
 
         [[5, 6, 7, 8, 9]]]),
 tensor([[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14]]]))

In [ ]:
# Perform element-wise addition
(a + b)


tensor([[[ 0,  2,  4,  6,  8],
         [ 5,  7,  9, 11, 13],
         [10, 12, 14, 16, 18]],

        [[ 5,  7,  9, 11, 13],
         [10, 12, 14, 16, 18],
         [15, 17, 19, 21, 23]]])

In [65]:
(a + b).shape

torch.Size([2, 3, 5])

# Compute the matrix multiplication of tensors with shapes:
(3, 4) and (4, 5)

(10, 3, 4) and (10, 4, 5) (Batch matrix multiplication)

In [66]:
a = torch.arange(12).view(3,4)
b = torch.arange(20).view(4,5)

torch.matmul(a, b)

tensor([[ 70,  76,  82,  88,  94],
        [190, 212, 234, 256, 278],
        [310, 348, 386, 424, 462]])

In [67]:
a = torch.rand(10, 3, 4)
b = torch.rand(10, 4, 5)

a.matmul(b).shape

torch.Size([10, 3, 5])

In [68]:
a.matmul(b)

tensor([[[0.7505, 1.0815, 1.3279, 1.0459, 0.6319],
         [0.4871, 0.4690, 0.6297, 0.4487, 0.4601],
         [0.9894, 0.3826, 0.9568, 0.2482, 1.1534]],

        [[1.4429, 0.9614, 1.8539, 1.2525, 0.8554],
         [1.1853, 0.9048, 1.8307, 1.0972, 0.7413],
         [1.2469, 0.9435, 1.8922, 1.3644, 0.7120]],

        [[1.2542, 1.3675, 1.5055, 1.4562, 1.4888],
         [0.7346, 0.8632, 0.6742, 0.5095, 0.8805],
         [1.3056, 1.2984, 1.3042, 1.4094, 1.3352]],

        [[0.9999, 1.0372, 0.7371, 0.9028, 1.0614],
         [0.9140, 0.8642, 0.6572, 0.7849, 0.7356],
         [1.0578, 1.0680, 0.7508, 0.9135, 1.0233]],

        [[0.7109, 1.5109, 0.9754, 1.0334, 0.7470],
         [0.3145, 0.9828, 0.3431, 0.4170, 0.0097],
         [1.2526, 1.8049, 1.1360, 0.8625, 0.5520]],

        [[0.4610, 0.4234, 0.5629, 0.5282, 0.7097],
         [0.8923, 0.4622, 0.9154, 0.5908, 0.9907],
         [0.4858, 0.5473, 0.8393, 0.7178, 1.1099]],

        [[1.6891, 0.4750, 1.3568, 0.8347, 0.7506],
         [1.3873, 0